src/Entity/Picture.php
<?php

namespace App\Entity;

use App\Repository\PictureRepository;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass=PictureRepository::class)
 */
class Picture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="photos", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        if ($imageFile !== null) {
            $this->updated_at = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Categorie
    {
        return $this->category;
    }

    public function setCategory(?Categorie $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsValidated(): ?bool
    {
        return $this->is_validated;
    }

    public function setIsValidated(bool $is_validated): self
    {
        $this->is_validated = $is_validated;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Picture;
use App\Repository\PictureRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        // getDoctrine()= connexion de la bdd - getRepository() = de l'entité Picture - 
        // findAll() retourne moi tout
        // $resultsPictures = $this->getDoctrine()->getRepository(Picture::class)->findAll();

        // Equivalent : SELECT * FROM picture WHERE is_valideted = true
        $resultsPictures = $this->getDoctrine()->getRepository(Picture::class)->findBy(['is_validated'=> true]);

        // Création du page par page
        // paginate() attend 3 arguments
            // 1. la collection contenatn tous les resultats ici toutes les images
            // 2. la page sur laquelle nous sommes, page 1 par défaut, envoyé par url getInt()
            // 3.le nombred 'élements par page
        $page = $request->query->getInt('page', 1);
        $pictures = $paginator->paginate(
            $resultsPictures, 
            $page === 0 ? 1: $page, 
            12
        );

        // Sélection de toutes le categories
        $categories = $this->getDoctrine()->getRepository(Categorie::class)->findAll();
        
        
        return $this->render('home/index.html.twig', [
            'pictures' => $pictures,
            'categories' => $categories
        ]);
         
    }
    /**
     * @Route("/category/{id}", name="pictures_by_category")
     */
    public function picturesByCategory($id, PaginatorInterface $paginator, Request $request)
    {
        // ddveut dire "Dump Data", arrête tout le chargement dès que le programme tombe dessus et affiche son contenu
        // équivalent de var dump(), lui laisse la page se charger complètement et affiche le contenu dans le debug bar
        // dd($id);

        // find() Sélectionne UN de la catégorie par son id
        $category = $this->getDoctrine()->getRepository(Categorie::class)->find($id);
        
        $query = $this->getDoctrine()->getRepository(Picture::class)->findBy([
            'category'=> $category,
            'is_validated'=> true
            ]);
           

          if(!$category){
              //  Si aucune photo n'est trouvé, nous créons une execption
              throw $this->createNotFoundException('Aucune photo dans cette catégorie');
          }

        // Création du page par page pour les images liées à la catégorie
        $page = $request->query->getInt('page', 1);
        $pictures = $paginator->paginate(
            // $category->getPictures(), 
            $query,
            $page === 0 ? 1: $page, 
            2
        );
          // Si des photos existent nous envoyons les données à la vue
          return $this->render('home/picturesByCategory.html.twig',  [
            // 'pictures' => $pictures,
            'category' => $category,
            'pictures' => $pictures
            ]
        );
    }

    /**
     * requirements permet de valider le type de la donnée passé en paramètre
     * Afficher l'image cliquée
     * @Route("/picture/{id}", name="picture_view", requirements={"id"="\d+"})
     * 
     */
    public function pictureView($id, PaginatorInterface $paginator, Request $request)
    {
        // dd($id);
         // find() Sélectionne UN de la catégorie par son id
         $picture = $this->getDoctrine()->getRepository(Picture::class)->find($id);
         $pictures = $this->getDoctrine()->getRepository(Picture::class)->findBy([
            'category'=> $category,
            'is_validated'=> true
            ]);
        
         if(!$picture){
            //  Si aucune photo n'est trouvé, nous créons une execption
            throw $this->createNotFoundException('Cette photo n\'existe pas');
        }
        // Création du page par page pour les images liées à la catégorie de l'image
        $page = $request->query->getInt('page', 1);
        $photos = $paginator->paginate(
        // $picture->getCategory()->getPictures(), 
        $pictures,
        $page === 0 ? 1: $page, 
            4
        );
        // Si des photos existent nous envoyons les données à la vue
        return $this->render('home/pictureView.html.twig',  [
            'picture' => $picture,
            'photos' => $photos
             
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Look Image!
{% endblock %}

{% block body %}

	{#  Liste des categories lien cliquable #}
	<ul class="nav justify-content-center py-4">
		{% for categorie in categories %}
		<li class="nav-item mx-2">
		{# path() contient le nom de la route vers laquelle nous souhaitons nous rediriger #}
			<a href="{{ path('pictures_by_category', { id: categorie.id } ) }}" class="nav-link" >
				{{ categorie.name }}
			</a>
		</li>
		{% endfor %}
	</ul>

	<h1>Accueil</h1>

	<div class="container">
		<div class="row">
			{#  for équivalant de foreach(), mais la condition est inversé #}
			{% for picture in pictures %}

				<div class="col-3 mb-4">
					<div class="card" >
						<a href="{{ path('picture_view', { id: picture.id } ) }}" >
						<img src="{{ asset('uploads/images/photos/'~ picture.image)|imagine_filter('thumbnail') }}" alt="{{ picture.image }}" class="rounded img-fluid">
						</a>
						<div class="card-body">
						<p>{{ picture.description }} </p>

						</div>
					</div>
				</div>
			{% endfor %}
			
		</div>
		<div class="nav justify-content-center py-4 mb-5 k">
        {{ knp_pagination_render(pictures) }}
    </div>
	
	</div>
	

{% endblock %}

templates/home/pictureView.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de la photo
	{{ picture.tags }}
{% endblock %}

{% block body %}
<h1>Aperçu de la photo</h1>
    {# <div class="py-4">
	    <a href="{{ path('home') }}"> retour à l'accueil</a>
    </div> #}
    <div class="container">
        <div class="row justify-content-center">
            <div class="card">
            <a href="{{ asset('uploads/images/photos/'~ picture.image) }}">
                <img src="{{ asset('uploads/images/photos/'~ picture.image)|imagine_filter('medium')  }}" alt="{{ picture.image }}" class=" rounded img-fluid">
            </a>
                    <div class="card-body">
                        <p>Publié le  {{ picture.createdAt |date('d/m/Y à h\\hi') }}</p>
                        <p>{{ picture.description }}</p>
                        <small>{{ picture.tags }}</small>
                        
                    </div>
            </div>
        </div>
        <hr class="mt-5">
        {#Afficherlesimagesdelamêmecategorie#}
        

            <h2>Photos de la catégorie {{ picture.category.name }}</h2>
            {# 
        "picture" correspond aux infos de notre image, à partir de cette image, nous allons chercher
        la catégorie reliée à l'image "picture.category" et à partir de cette catégorie, nous avons la
        possibilité de récupérer toutes les images liées à cette même catégorie "picture.category.pictures"
    #}
            <div class="row">
                {% for photo in photos %}
               {#  
                !== s'écrit en Twig : is not same as()
                === s'écrit en Twig : is same as()
                 #}
                      {% if photo.image is not same as(picture.image)  %}
                    <div class="col-3 mb-4">
                        <a href="{{ path('picture_view', { id: photo.id }) }}">
                            <img src="{{ asset('uploads/images/photos/'~ photo.image)|imagine_filter('thumbnail') }}" alt="{{ photo.image }}" class="rounded img-fluid">
                        </a>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        <div class="nav justify-content-center py-4 mb-5 k">
            {{ knp_pagination_render(photos) }}
        </div>
    </div>
    


{% endblock %}

templates/home/picturesByCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Photos de la catégorie "{{ category.name }}" {% endblock %}

{% block body %}
{# <div class="py-4">
	    <a href="{{ path('home') }}"> retour à l'accueil</a>
</div> #}

{# Pas besoin de boucle si on selectionne un seul enregistrement en BDD (comme fetch()) #}
<h1>Catégorie "{{ category.name }}"</h1>

	<div class="container">
		<div class="row">
			{#  for équivalant de foreach(), mais la condition est inversé #}
			{% for picture in pictures %}

				<div class="col-6 mb-4">
					<div class="card" style="width: 15rem;">
					<a href="{{ path('picture_view', { id: picture.id } ) }}" >
						<img src="{{ asset('uploads/images/photos/'~ picture.image)|imagine_filter('thumbnail') }}" alt="{{ picture.image }}" class="img-fluid">
						</a>
						<div class="card-body">
						<p>{{ picture.description }} </p>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		<div class="nav justify-content-center py-4 mb-5 k">
        {{ knp_pagination_render(pictures) }}
    </div>

	</div>
{% endblock %}